# Generated by Django 2.1.5 on 2019-02-01 06:26

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190131_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=500, validators=[posts.validators.validate_blank_content]),
        ),
    ]
